// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/webook-project-go/webook-comment/grpc"
	"github.com/webook-project-go/webook-comment/ioc"
	"github.com/webook-project-go/webook-comment/repository"
	"github.com/webook-project-go/webook-comment/repository/cache"
	"github.com/webook-project-go/webook-comment/repository/dao"
	"github.com/webook-project-go/webook-comment/service"
)

// Injectors from wire.go:

func NewApp() *App {
	client := ioc.InitEtcd()
	grpcxServer := ioc.InitGrpcServer(client)
	db := ioc.InitDatabase()
	daoDao := dao.NewDao(db)
	cmdable := ioc.InitRedis()
	cacheCache := cache.NewRedisCache(cmdable)
	repositoryRepository := repository.NewRepository(daoDao, cacheCache)
	serviceService := service.NewService(repositoryRepository)
	grpcService := grpc.NewService(serviceService)
	app := &App{
		Server:  grpcxServer,
		Service: grpcService,
	}
	return app
}

// wire.go:

var thirdPartyProvider = wire.NewSet(ioc.InitDatabase, ioc.InitRedis, ioc.InitEtcd, ioc.InitGrpcServer)

var commentServiceProvider = wire.NewSet(dao.NewDao, cache.NewRedisCache, repository.NewRepository, service.NewService)
